package viewAdimnistrador;


import dao.ClienteDAO;
import dao.EstoqueDAO;
import dao.FornecedorDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Cliente;
import model.EstoqueModel;
import model.Fornecedor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form EstoqueModel
     */
    public Estoque() {
        initComponents();
        this.setSize(580,510);
        this.setLocationRelativeTo(null);
         DefaultTableModel modelo= (DefaultTableModel) tableEstoque.getModel();
       tableEstoque.setRowSorter( new TableRowSorter(modelo));
       readTableEstoque();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEstoque = new javax.swing.JPanel();
        btnInserirItem = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstoque = new javax.swing.JTable();
        txtItem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Estoque");
        setResizable(false);
        getContentPane().setLayout(null);

        pnlEstoque.setBackground(new java.awt.Color(255, 204, 102));
        pnlEstoque.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlEstoque.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlEstoque.setLayout(null);

        btnInserirItem.setText("Inserir");
        btnInserirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirItemActionPerformed(evt);
            }
        });
        pnlEstoque.add(btnInserirItem);
        btnInserirItem.setBounds(30, 120, 80, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.setPreferredSize(new java.awt.Dimension(63, 23));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlEstoque.add(btnAlterar);
        btnAlterar.setBounds(140, 120, 100, 23);

        tableEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Item", "Preço", "Quantidade", "FornecedorID"
            }
        ));
        tableEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEstoque);

        pnlEstoque.add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 452, 210);

        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });
        pnlEstoque.add(txtItem);
        txtItem.setBounds(20, 30, 141, 20);

        jLabel1.setText("Item");
        pnlEstoque.add(jLabel1);
        jLabel1.setBounds(20, 10, 50, 14);

        jLabel2.setText("Preço");
        pnlEstoque.add(jLabel2);
        jLabel2.setBounds(190, 10, 50, 14);

        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });
        pnlEstoque.add(txtQtd);
        txtQtd.setBounds(20, 80, 141, 20);

        jLabel3.setText("Quantidade");
        pnlEstoque.add(jLabel3);
        jLabel3.setBounds(20, 60, 90, 14);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        pnlEstoque.add(txtPreco);
        txtPreco.setBounds(190, 30, 141, 20);

        jLabel4.setText("Fornecedor ID");
        pnlEstoque.add(jLabel4);
        jLabel4.setBounds(190, 60, 90, 14);

        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });
        pnlEstoque.add(txtFornecedor);
        txtFornecedor.setBounds(190, 80, 70, 20);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        pnlEstoque.add(btnVoltar);
        btnVoltar.setBounds(20, 380, 90, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlEstoque.add(btnExcluir);
        btnExcluir.setBounds(260, 120, 110, 23);

        getContentPane().add(pnlEstoque);
        pnlEstoque.setBounds(0, 0, 580, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tableEstoque.getSelectedRow() !=-1)
    {
     EstoqueModel c=new EstoqueModel();
        EstoqueDAO dao=new EstoqueDAO();
        c.setItemdeestoque(txtItem.getText());
        int intQtd=Integer.parseInt(txtQtd.getText());
        c.setQuantidade(intQtd);
         int intPreco=Integer.parseInt(txtPreco.getText());
        c.setPreco(intPreco);
        int intFornecedor=Integer.parseInt(txtFornecedor.getText());
        c.setFornecedor(intFornecedor);
        
       
        c.setCodigo((int)tableEstoque.getValueAt(tableEstoque.getSelectedRow(),0));
        dao.alterar(c);
        
        readTableEstoque();
    txtItem.setText("");
        txtQtd.setText("");
        txtPreco.setText("");
        txtFornecedor.setText("");
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
         MenuAdministrador a= new MenuAdministrador();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnInserirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirItemActionPerformed
       EstoqueModel c=new EstoqueModel();
        EstoqueDAO dao=new EstoqueDAO();
        
        c.setItemdeestoque(txtItem.getText());
        int intQtd=Integer.parseInt(txtQtd.getText());
        c.setQuantidade(intQtd);
         int intPreco=Integer.parseInt(txtPreco.getText());
        c.setPreco(intPreco);
        int intFornecedor=Integer.parseInt(txtFornecedor.getText());
        c.setFornecedor(intFornecedor);

        dao.adicionar(c);
        txtItem.setText("");
        txtQtd.setText("");
        txtPreco.setText("");
        txtFornecedor.setText("");
        readTableEstoque();
    }//GEN-LAST:event_btnInserirItemActionPerformed

    private void tableEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstoqueMouseClicked
       if (tableEstoque.getSelectedRow() !=-1)
    {
    
    txtItem.setText(tableEstoque.getValueAt(tableEstoque.getSelectedRow(), 1).toString());
    txtPreco.setText(tableEstoque.getValueAt(tableEstoque.getSelectedRow(), 2).toString());
    txtQtd.setText(tableEstoque.getValueAt(tableEstoque.getSelectedRow(), 3).toString());
    txtFornecedor.setText(tableEstoque.getValueAt(tableEstoque.getSelectedRow(), 4).toString());
    }
    }//GEN-LAST:event_tableEstoqueMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tableEstoque.getSelectedRow() !=-1)
    {
     EstoqueModel c=new EstoqueModel();
        EstoqueDAO dao=new EstoqueDAO();
      
        
       
        c.setCodigo((int)tableEstoque.getValueAt(tableEstoque.getSelectedRow(),0));
        dao.eliminar(c);
        
        readTableEstoque();
        txtItem.setText("");
        txtQtd.setText("");
        txtPreco.setText("");
        txtFornecedor.setText("");
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    public void readTableEstoque(){
       DefaultTableModel modelo= (DefaultTableModel) tableEstoque.getModel();
       modelo.setNumRows(0);
       tableEstoque.getColumnModel().getColumn(0).setPreferredWidth(50);
       tableEstoque.getColumnModel().getColumn(1).setPreferredWidth(250);
       tableEstoque.getColumnModel().getColumn(2).setPreferredWidth(250);
       tableEstoque.getColumnModel().getColumn(3).setPreferredWidth(250);
       tableEstoque.getColumnModel().getColumn(4).setPreferredWidth(300);
      
       EstoqueDAO dao=new EstoqueDAO();
       
       for(EstoqueModel c: dao.Read()){
       
       modelo.addRow(new Object[]{
       c.getCodigo(),
       c.getItemdeestoque(),
       c.getPreco(),
       c.getQuantidade(),
       c.getFornecedor()
       
       });
       
       
       }
    
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirItem;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlEstoque;
    private javax.swing.JTable tableEstoque;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
