package viewAdimnistrador;


import dao.FornecedorDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Fornecedor;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class Fornecedores extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeFornecedores
     */
    public Fornecedores() {
        initComponents();
        this.setLocationRelativeTo(this);
           this.setSize(570,600);
        DefaultTableModel modelo= (DefaultTableModel) tableFornecedores.getModel();
       tableFornecedores.setRowSorter( new TableRowSorter(modelo));
       readTableFornecedores();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnInserirFornecedor = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFornecedores = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fornecedores");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(null);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(160, 140, 90, 23);

        btnInserirFornecedor.setText("Inserir");
        btnInserirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirFornecedor);
        btnInserirFornecedor.setBounds(30, 140, 100, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(290, 140, 80, 23);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(20, 490, 110, 23);

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(30, 100, 169, 20);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(210, 100, 170, 20);

        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 130, 14);

        jLabel2.setText("Endereco");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 30, 130, 14);

        jLabel4.setText("Telefone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 80, 140, 14);

        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 80, 130, 14);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(329, 191, 0, 0);

        tableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereco", "Telefone", "Email"
            }
        ));
        tableFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFornecedores);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 410, 300);
        jPanel1.add(txtNome);
        txtNome.setBounds(30, 50, 180, 20);
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(220, 50, 169, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       if (tableFornecedores.getSelectedRow() !=-1)
    {
     Fornecedor c=new Fornecedor();
        FornecedorDAO dao=new FornecedorDAO();
        
        c.setNome(txtNome.getText());
        int intTelefone=Integer.parseInt(txtTelefone.getText());
        c.setTelefone(intTelefone);
        c.setEndereco(txtEndereco.getText());
        c.setEmail(txtEmail.getText());
       
        c.setIdFornecedor((int)tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(),0));
        dao.alterar(c);
        txtNome.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        readTableFornecedores();
    
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
          MenuAdministrador a= new MenuAdministrador();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnInserirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFornecedorActionPerformed
            Fornecedor c=new Fornecedor();
        FornecedorDAO dao=new FornecedorDAO();
        
        c.setNome(txtNome.getText());
        int intTelefone=Integer.parseInt(txtTelefone.getText());
        c.setTelefone(intTelefone);
        c.setEndereco(txtEndereco.getText());
        c.setEmail(txtEmail.getText());
        dao.adicionar(c);
        readTableFornecedores();
    }//GEN-LAST:event_btnInserirFornecedorActionPerformed

    private void tableFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFornecedoresMouseClicked
        if (tableFornecedores.getSelectedRow() !=-1)
    {
    
    txtNome.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 1).toString());
    txtEndereco.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 2).toString());
    txtTelefone.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 3).toString());
    txtEmail.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 4).toString());
    }
    }//GEN-LAST:event_tableFornecedoresMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tableFornecedores.getSelectedRow() !=-1)
    {
     Fornecedor c=new Fornecedor();
        FornecedorDAO dao=new FornecedorDAO();
        
        
       
        c.setIdFornecedor((int)tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(),0));
        dao.eliminar(c);
        txtNome.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        readTableFornecedores();
    
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser excluída!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
public void readTableFornecedores(){
       DefaultTableModel modelo= (DefaultTableModel) tableFornecedores.getModel();
       modelo.setNumRows(0);
       tableFornecedores.getColumnModel().getColumn(0).setPreferredWidth(50);
       tableFornecedores.getColumnModel().getColumn(1).setPreferredWidth(250);
       tableFornecedores.getColumnModel().getColumn(2).setPreferredWidth(250);
       tableFornecedores.getColumnModel().getColumn(3).setPreferredWidth(250);
       tableFornecedores.getColumnModel().getColumn(4).setPreferredWidth(300);
       
       FornecedorDAO dao=new FornecedorDAO();
       
       for(Fornecedor c: dao.Read()){
       
       modelo.addRow(new Object[]{
       c.getIdFornecedor(),
       c.getNome(),
       c.getEndereco(),
       c.getTelefone(),
       c.getEmail(),
       });
       
       
       }
    
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirFornecedor;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFornecedores;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
