package viewAdimnistrador;

import dao.FuncionarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Funcionario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeFuncionario
     */
    public Funcionarios() {
        initComponents();
        this.setLocationRelativeTo(this);
           this.setSize(800,600);
           DefaultTableModel modelo= (DefaultTableModel) tableFuncionarios.getModel();
       tableFuncionarios.setRowSorter( new TableRowSorter(modelo));
       readTableFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        btnInserirFuncio = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        ntnVoltar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtMorada = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuncionarios = new javax.swing.JTable();
        txtFuncao = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Funcionários");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(null);

        btnInserirFuncio.setText("Inserir");
        btnInserirFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFuncioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirFuncio);
        btnInserirFuncio.setBounds(120, 130, 100, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(250, 130, 80, 23);

        ntnVoltar.setText("Voltar");
        ntnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(ntnVoltar);
        ntnVoltar.setBounds(10, 480, 80, 23);
        jPanel1.add(txtNome);
        txtNome.setBounds(80, 40, 157, 20);
        jPanel1.add(txtMorada);
        txtMorada.setBounds(260, 40, 160, 20);
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(450, 40, 160, 20);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(80, 90, 160, 20);

        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 100, 14);

        jLabel3.setText("Morada");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 20, 110, 14);

        jLabel4.setText("Telefone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 20, 110, 14);

        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 70, 100, 14);

        jLabel6.setText("Funcao");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 70, 110, 14);

        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 70, 100, 14);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(cmbSexo);
        cmbSexo.setBounds(450, 90, 90, 20);

        tableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Morada", "Telefone", "Email", "Sexo", "Função"
            }
        ));
        tableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFuncionarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 680, 300);

        txtFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFuncao);
        txtFuncao.setBounds(260, 90, 160, 20);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(360, 130, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tableFuncionarios.getSelectedRow() !=-1)
    {
     Funcionario c=new Funcionario();
        FuncionarioDAO dao=new FuncionarioDAO();
        
        c.setNome(txtNome.getText());
        int intTelefone=Integer.parseInt(txtTelefone.getText());
        c.setTelefone(intTelefone);
        c.setMorada(txtMorada.getText());
        c.setFuncao(txtFuncao.getText());
        c.setEmail(txtEmail.getText());
        c.setSexo((String) cmbSexo.getSelectedItem());
        c.setIdFuncionario((int)tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(),0));
        dao.alterar(c);
        txtNome.setText("");
        txtMorada.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        readTableFuncionarios();
    
    }else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        } 
            
       
            
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncaoActionPerformed

    private void ntnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntnVoltarActionPerformed
        // TODO add your handling code here:
         MenuAdministrador a= new MenuAdministrador();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_ntnVoltarActionPerformed

    private void btnInserirFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFuncioActionPerformed
       Funcionario c=new Funcionario();
        FuncionarioDAO dao=new FuncionarioDAO();
        
        c.setNome(txtNome.getText());
        int intTelefone=Integer.parseInt(txtTelefone.getText());
        c.setTelefone(intTelefone);
        c.setMorada(txtMorada.getText());
        c.setEmail(txtEmail.getText());
        c.setSexo((String) cmbSexo.getSelectedItem());
        c.setFuncao(txtFuncao.getText());
        
        dao.adicionar(c);
        readTableFuncionarios();
    }//GEN-LAST:event_btnInserirFuncioActionPerformed

    private void tableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFuncionariosMouseClicked
        if (tableFuncionarios.getSelectedRow() !=-1)
    {
    
    txtNome.setText(tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(), 1).toString());
    txtMorada.setText(tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(), 2).toString());
    txtTelefone.setText(tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(), 3).toString());
    txtEmail.setText(tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(), 4).toString());
    txtFuncao.setText(tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(), 5).toString());
    }
    }//GEN-LAST:event_tableFuncionariosMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         if (tableFuncionarios.getSelectedRow() !=-1)
    {
     Funcionario c=new Funcionario();
        FuncionarioDAO dao=new FuncionarioDAO();
        
       
        c.setIdFuncionario((int)tableFuncionarios.getValueAt(tableFuncionarios.getSelectedRow(),0));
        dao.eliminar(c);
        txtNome.setText("");
        txtMorada.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        readTableFuncionarios();
    
    }else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser excluída!", "erro", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_btnExcluirActionPerformed

   public void readTableFuncionarios(){
    DefaultTableModel modelo= (DefaultTableModel) tableFuncionarios.getModel();
       modelo.setNumRows(0);
       tableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(50);
       tableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(250);
       tableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(250);
       tableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(250);
       tableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(300);
       tableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(80);
       tableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(300);
       FuncionarioDAO dao=new FuncionarioDAO();
       
       for(Funcionario c: dao.Read()){
       
       modelo.addRow(new Object[]{
       c.getIdFuncionario(),
       c.getNome(),
       c.getMorada(),
       c.getTelefone(),
       c.getEmail(),
       c.getSexo(),
       c.getFuncao()
       });
       
       
       }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirFuncio;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ntnVoltar;
    private javax.swing.JTable tableFuncionarios;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
