package viewAdimnistrador;

import viewUsuarioComum.MenuUsuarioComum;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.log.Log;
import java.sql.*;

import conexao.Conexao;
import dao.ExtrasMarcacao;
import dao.MarcacaoDAO;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.List;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.MarcacaoModel;
import model.Cliente;
import model.Servico;
import model.Usuario;
import javax.swing.text.Document;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class Marcacao extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Marcacao() {
        initComponents();
        
           this.setSize(800,500);
           this.setLocationRelativeTo(null);
            DefaultTableModel modelo= (DefaultTableModel) tableMarcacao.getModel();
       tableMarcacao.setRowSorter( new TableRowSorter(modelo));
       readTableMarcacao();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInserirMarcacao = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMarcacao = new javax.swing.JTable();
        txtClienteId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtServicoId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHora_ = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtData_ = new javax.swing.JFormattedTextField();
        btnFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Marcações");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        btnInserirMarcacao.setText("Inserir");
        btnInserirMarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirMarcacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirMarcacao);
        btnInserirMarcacao.setBounds(30, 80, 110, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(290, 80, 90, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(160, 80, 110, 23);

        tableMarcacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº", "CódigoServico", "Descricao", "ClienteID", "Nome ", "Data", "Hora"
            }
        ));
        tableMarcacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMarcacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMarcacao);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 690, 241);

        txtClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtClienteId);
        txtClienteId.setBounds(140, 40, 90, 20);

        jLabel2.setText("CódigoServico");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 140, 14);

        jLabel3.setText("Cliente ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 20, 150, 14);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(30, 400, 100, 23);

        txtServicoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtServicoId);
        txtServicoId.setBounds(30, 40, 90, 20);

        jLabel1.setText("Data ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 20, 110, 14);

        txtHora_.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(txtHora_);
        txtHora_.setBounds(410, 40, 110, 20);

        jLabel4.setText("Hora");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 20, 70, 14);

        txtData_.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(txtData_);
        txtData_.setBounds(260, 40, 130, 20);

        btnFactura.setText("Emitir fatura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactura);
        btnFactura.setBounds(400, 80, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void txtClienteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteIdActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuAdministrador a= new MenuAdministrador();
        a.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    private void btnInserirMarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirMarcacaoActionPerformed
        try {                                                   
            MarcacaoModel c=new MarcacaoModel();
            MarcacaoDAO dao=new MarcacaoDAO();
            ExtrasMarcacao e=new ExtrasMarcacao();
            Cliente cliente=new Cliente();
            Servico servico=new Servico();
            
            cliente.setIdCliente(Integer.parseInt(txtClienteId.getText()));
            servico.setCodigo(Integer.parseInt(txtServicoId.getText()));
            String cli=e.obterClienteName(cliente);
            String serv=e.obterServicoDescricao(servico);
            c.setCliente(cli);
            
            c.setServico(serv);
            c.setCodServico(Integer.parseInt(txtServicoId.getText()));
            c.setIdCliente(Integer.parseInt(txtClienteId.getText()));
            
            String dataString=txtData_.getText();
            DateFormat fmt = new SimpleDateFormat("dd-MM-yyyy");
            java.sql.Date data = null;
            try {
                data = new java.sql.Date(fmt.parse(dataString).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            c.setData_(data);
            
            String s = txtHora_.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("H:mm");
            long ms = sdf.parse(s).getTime();
            Time t = new Time(ms);
            c.setHora_(t);
            dao.adicionar(c);
            readTableMarcacao();
            
            
        } catch (ParseException ex) {
            Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                              
    }//GEN-LAST:event_btnInserirMarcacaoActionPerformed

    public void readTableMarcacao(){
       DefaultTableModel modelo= (DefaultTableModel) tableMarcacao.getModel();
       modelo.setNumRows(0);
       tableMarcacao.getColumnModel().getColumn(0).setPreferredWidth(20);
       tableMarcacao.getColumnModel().getColumn(1).setPreferredWidth(50);
       tableMarcacao.getColumnModel().getColumn(2).setPreferredWidth(100);
       tableMarcacao.getColumnModel().getColumn(3).setPreferredWidth(20);
        tableMarcacao.getColumnModel().getColumn(4).setPreferredWidth(100);
        tableMarcacao.getColumnModel().getColumn(5).setPreferredWidth(45);
        tableMarcacao.getColumnModel().getColumn(6).setPreferredWidth(45);
      
       MarcacaoDAO dao=new MarcacaoDAO();
       
       for(MarcacaoModel c: dao.Read()){
       
       modelo.addRow(new Object[]{
       c.getNumero(),
           c.getCodServico(),
      
       c.getServico(),
       c.getIdCliente(),
        c.getCliente(),
       c.getData_(),
      c.getHora_(),
      
      
       
       });
       
       
       }
    
       }
    private void txtServicoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoIdActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tableMarcacao.getSelectedRow() !=-1)
    {
        MarcacaoModel c=new MarcacaoModel();
            MarcacaoDAO dao=new MarcacaoDAO();
            ExtrasMarcacao e=new ExtrasMarcacao();
            Cliente cliente=new Cliente();
            Servico servico=new Servico();
            
            cliente.setIdCliente(Integer.parseInt(txtClienteId.getText()));
            servico.setCodigo(Integer.parseInt(txtServicoId.getText()));
            String cli=e.obterClienteName(cliente);
            String serv=e.obterServicoDescricao(servico);
            c.setCliente(cli);
            
            c.setServico(serv);
            int intServico=(Integer.parseInt(txtServicoId.getText()));
            c.setCodServico(intServico);
            int intCliente=(Integer.parseInt(txtClienteId.getText()));
           c.setIdCliente(intCliente);
            String dataString=txtData_.getText();
            DateFormat fmt = new SimpleDateFormat("dd-MM-yyyy");
            java.sql.Date data = null;
            try {
                data = new java.sql.Date(fmt.parse(dataString).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            c.setData_(data);
            
            String s = txtHora_.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("H:mm");
            long ms = 0;
            try {
                ms = sdf.parse(s).getTime();
            } catch (ParseException ex) {
                Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            Time t = new Time(ms);
            c.setHora_(t);
     
        
        
       
        c.setNumero((int)tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(),0));
        dao.alterar(c);
        readTableMarcacao();
    
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tableMarcacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMarcacaoMouseClicked
       if (tableMarcacao.getSelectedRow() !=-1)
    {
     txtServicoId.setText(tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(), 1).toString());
    txtClienteId.setText(tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(), 3).toString());
    
    txtData_.setText(tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(), 5).toString());
    txtHora_.setText(tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(), 6).toString());
    
    }
   
    }//GEN-LAST:event_tableMarcacaoMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tableMarcacao.getSelectedRow() !=-1)
    {
        MarcacaoModel c=new MarcacaoModel();
            MarcacaoDAO dao=new MarcacaoDAO();
            ExtrasMarcacao e=new ExtrasMarcacao();
            Cliente cliente=new Cliente();
            Servico servico=new Servico();
            
        
        
       
        c.setNumero((int)tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(),0));
        dao.eliminar(c);
        
    
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser excluida!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        if (tableMarcacao.getSelectedRow() !=-1)
    {
            try {
                MarcacaoModel c=new MarcacaoModel();
                MarcacaoDAO dao=new MarcacaoDAO();
                ExtrasMarcacao e=new ExtrasMarcacao();
                Cliente cliente=new Cliente();
                Servico servico=new Servico();
                
                
                
                
                servico.setCodigo((int)tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(),1));
                String Preco=Integer.toString( e.obterServicoPreco(servico));
                Document doc=new javax.swing.text.Document();
                
                MarcacaoDAO m= new MarcacaoDAO();
                
                
                String arquivoPDF="Recibo.pdf";
                
                
                PdfWriter.getInstance(doc, new FileOutputStream(arquivoPDF));
                doc.open();
                Paragraph p=new Paragraph("Recibo PDF");
                p.setAlignment(1);
                doc.add(p);
                p=new Paragraph("");
                doc.add(p);
                p=new Paragraph("Data e Hora:");
                doc.add(p);
                LocalDateTime localDateTime = LocalDateTime.now();
                String Data_hora=localDateTime.toString();
                p=new Paragraph(Data_hora);
                doc.add(p);
                p=new Paragraph("Cliente:");
                doc.add(p);
                String Cliente=tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(), 4).toString();
                
                p=new Paragraph(Cliente);
                doc.add(p);
                p=new Paragraph("");
                doc.add(p);
                p=new Paragraph("");
                doc.add(p);
                p=new Paragraph("");
                doc.add(p);
                p=new Paragraph("");
                doc.add(p);
                p=new Paragraph("Serviço:");
                doc.add(p);
                String Servico=tableMarcacao.getValueAt(tableMarcacao.getSelectedRow(), 2).toString();
                p=new Paragraph(Servico);
                doc.add(p);
                p=new Paragraph("Preço:");
                doc.add(p);
                p=new Paragraph(Preco);
                doc.add(p);
                doc.close();
                Desktop.getDesktop().open(new File(arquivoPDF));
            } catch (DocumentException ex) {
                Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Marcacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    
    }
       else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser manipulada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marcacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnInserirMarcacao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMarcacao;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JFormattedTextField txtData_;
    private javax.swing.JFormattedTextField txtHora_;
    private javax.swing.JTextField txtServicoId;
    // End of variables declaration//GEN-END:variables
}
