/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewAdimnistrador;

import viewControl.Login;
import conexao.Conexao;
import java.awt.EventQueue;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Marcia Daniel
 */
public class MenuAdministrador extends javax.swing.JFrame {
    
    /**
     * Creates new form testeFrame
     */
    public MenuAdministrador() {
        initComponents();
        this.setSize(760,494);
         setLocationRelativeTo( null );
        
      
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblTipoUsuario=new javax.swing.JLabel();
        lblUsuario=new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFornecedores = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnMarcacao = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnMovimentos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 494));
        setResizable(false);
        setSize(new java.awt.Dimension(760, 494));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(205, 95, 0, 0);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(876, 101, 0, 0);
        lblUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFornecedores.setBackground(new java.awt.Color(255, 255, 204));
        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/fornecedores.png"))); // NOI18N
        btnFornecedores.setText("Fornecedores");
        btnFornecedores.setBorder(null);
        btnFornecedores.setBorderPainted(false);
        btnFornecedores.setFocusPainted(false);
        btnFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedores.setIconTextGap(30);
        btnFornecedores.setSelected(true);
        btnFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnFornecedores);
        btnFornecedores.setBounds(80, 240, 150, 150);

        btnClientes.setBackground(new java.awt.Color(255, 255, 204));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/clientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setFocusPainted(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setIconTextGap(30);
        btnClientes.setSelected(true);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientes);
        btnClientes.setBounds(80, 60, 150, 150);

        btnFuncionarios.setBackground(new java.awt.Color(255, 255, 204));
        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/funcionarios.png"))); // NOI18N
        btnFuncionarios.setText("Funcionários");
        btnFuncionarios.setBorder(null);
        btnFuncionarios.setBorderPainted(false);
        btnFuncionarios.setFocusPainted(false);
        btnFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFuncionarios.setIconTextGap(30);
        btnFuncionarios.setSelected(true);
        btnFuncionarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnFuncionarios);
        btnFuncionarios.setBounds(260, 60, 150, 150);

        btnMarcacao.setBackground(new java.awt.Color(255, 255, 204));
        btnMarcacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/marcacao2.png"))); // NOI18N
        btnMarcacao.setText("Marcações");
        btnMarcacao.setBorder(null);
        btnMarcacao.setBorderPainted(false);
        btnMarcacao.setFocusPainted(false);
        btnMarcacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMarcacao.setIconTextGap(30);
        btnMarcacao.setSelected(true);
        btnMarcacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcacaoActionPerformed(evt);
            }
        });
        jPanel2.add(btnMarcacao);
        btnMarcacao.setBounds(260, 240, 150, 150);

        btnServicos.setBackground(new java.awt.Color(255, 255, 204));
        btnServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/servicos.png"))); // NOI18N
        btnServicos.setText("Serviços");
        btnServicos.setBorder(null);
        btnServicos.setBorderPainted(false);
        btnServicos.setFocusPainted(false);
        btnServicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServicos.setIconTextGap(30);
        btnServicos.setSelected(true);
        btnServicos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });
        jPanel2.add(btnServicos);
        btnServicos.setBounds(430, 60, 150, 150);

        btnMovimentos.setBackground(new java.awt.Color(255, 255, 204));
        btnMovimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/movimentos2.png"))); // NOI18N
        btnMovimentos.setText("Movimentos");
        btnMovimentos.setBorder(null);
        btnMovimentos.setBorderPainted(false);
        btnMovimentos.setFocusPainted(false);
        btnMovimentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMovimentos.setIconTextGap(30);
        btnMovimentos.setSelected(true);
        btnMovimentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMovimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimentosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMovimentos);
        btnMovimentos.setBounds(430, 240, 150, 150);

        btnSair.setBackground(new java.awt.Color(255, 204, 102));
        btnSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcia Daniel\\Downloads\\sair.png")); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair);
        btnSair.setBounds(600, 400, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
     Funcionarios a= new Funcionarios();
     a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        int Confirm = JOptionPane.showConfirmDialog(null,"Deseja terminar sessão?","Terminar sessão", JOptionPane.YES_NO_OPTION);
    if (Confirm == JOptionPane.YES_OPTION) {
        Login a=new Login();
                a.setVisible(true);
        this.dispose();
    } else if (Confirm == JOptionPane.NO_OPTION){
      setDefaultCloseOperation(MenuAdministrador.DO_NOTHING_ON_CLOSE);

    }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
       Clientes a= new Clientes();
     a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
  Fornecedores a= new Fornecedores();
     a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnMarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcacaoActionPerformed
        Marcacao a= new Marcacao();
     a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMarcacaoActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
         Servicos a= new Servicos();
     a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnMovimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimentosActionPerformed
       
    Movimentos m=new Movimentos();
    m.setVisible(true);
    this.dispose();
               
       
        
    }//GEN-LAST:event_btnMovimentosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        


                  
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnMarcacao;
    private javax.swing.JButton btnMovimentos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblTipoUsuario;
    
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
