package viewAdimnistrador;

import dao.CaixaDAO;
import dao.MovimentoDAO;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Caixa;
import model.Movimento;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class Movimentos extends javax.swing.JFrame {

    /**
     * Creates new form FluxoDeCaixa
     */
    public Movimentos() {
        initComponents();
        this.setSize(600,510);
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo= (DefaultTableModel) tableMovimentos.getModel();
       tableMovimentos.setRowSorter( new TableRowSorter(modelo));
       readTableMovimentos();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpnSaldo = new javax.swing.JTextPane();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMovimentos = new javax.swing.JTable();
        btnInserirMovimento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Movimentos");
        setLocation(new java.awt.Point(0, 0));
        setName("FluxoDeCaixa"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(null);
        jPanel1.add(tpnSaldo);
        tpnSaldo.setBounds(260, 440, 130, 20);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(50, 440, 75, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Saldo Actual:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 440, 100, 15);

        tableMovimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Data e Hora", "Valor", "Tipo"
            }
        ));
        tableMovimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMovimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMovimentos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 149, 500, 250);

        btnInserirMovimento.setText("Registrar");
        btnInserirMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirMovimentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirMovimento);
        btnInserirMovimento.setBounds(110, 120, 90, 23);

        jLabel1.setText("Descrição");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 80, 14);
        jPanel1.add(txtDescricao);
        txtDescricao.setBounds(40, 30, 210, 20);

        jLabel2.setText("Valor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 80, 14);
        jPanel1.add(txtValor);
        txtValor.setBounds(40, 80, 130, 20);

        jLabel6.setText("Tipo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 60, 50, 10);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saída" }));
        jPanel1.add(cmbTipo);
        cmbTipo.setBounds(200, 80, 80, 20);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(220, 120, 110, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(350, 120, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
      MenuAdministrador a=new MenuAdministrador();
      a.setVisible(true);
      dispose();
      
    }//GEN-LAST:event_btnVoltarActionPerformed
    public int atualizarSaldo(String tipo, int value)
    {
        Movimento c=new Movimento();
        
    CaixaDAO cx=new CaixaDAO();
        Caixa s=new Caixa();
        int  Saldo=cx.obterSaldo(s);
       if(tipo=="Entrada")
           Saldo=Saldo+(value);
       else
       {
           Saldo=Saldo-(value);
       }
       s.setSaldo(Saldo);
        cx.ActualizarSaldo(s);
        return Saldo;
        
       
    }
    private void btnInserirMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirMovimentoActionPerformed
        Movimento c=new Movimento();
        MovimentoDAO dao=new MovimentoDAO();
        CaixaDAO cx=new CaixaDAO();
        Caixa s=new Caixa();
       
       
        c.setDescricao(txtDescricao.getText());
        int intValor=Integer.parseInt(txtValor.getText());
       c.setValor(intValor);
       c.setTipo((String) cmbTipo.getSelectedItem());
        java.util.Date now = new java.util.Date();
    Timestamp current = new java.sql.Timestamp(now.getTime()); 
       c.setData_hora(current);
        dao.adicionar(c);
        
        String tipo=(String) cmbTipo.getSelectedItem();
        int value=Integer.parseInt(txtValor.getText());
       int saldo=atualizarSaldo(tipo,value);
        readTableMovimentos();
        
        String t=Integer.toString(saldo);
        
        tpnSaldo.setText(t);
    }//GEN-LAST:event_btnInserirMovimentoActionPerformed

    private void tableMovimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMovimentosMouseClicked
       if (tableMovimentos.getSelectedRow() !=-1)
    {
    
    txtDescricao.setText(tableMovimentos.getValueAt(tableMovimentos.getSelectedRow(), 1).toString());
    txtValor.setText(tableMovimentos.getValueAt(tableMovimentos.getSelectedRow(), 3).toString());
    cmbTipo.setSelectedItem(tableMovimentos.getValueAt(tableMovimentos.getSelectedRow(), 4));
    }
    
    }//GEN-LAST:event_tableMovimentosMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       if (tableMovimentos.getSelectedRow() !=-1)
    {
     Movimento c=new Movimento();
        MovimentoDAO dao=new MovimentoDAO();
        Caixa s=new Caixa();
        c.setDescricao(txtDescricao.getText());
        int intValor=Integer.parseInt(txtValor.getText());
        c.setValor(intValor);
        c.setTipo((String) cmbTipo.getSelectedItem());
        c.setNumero((int)tableMovimentos.getValueAt(tableMovimentos.getSelectedRow(),0));
        dao.alterar(c);
        
        
        String tipo=(String) cmbTipo.getSelectedItem();
        int value=Integer.parseInt(txtValor.getText());
       int saldo=atualizarSaldo(tipo,value);
        readTableMovimentos();
        
        String t=Integer.toString(saldo);
        
        tpnSaldo.setText(t);
    
    }else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tableMovimentos.getSelectedRow() !=-1)
    {
     Movimento c=new Movimento();
        MovimentoDAO dao=new MovimentoDAO();
        Caixa s=new Caixa();
       CaixaDAO cx=new CaixaDAO();
      
        c.setNumero((int)tableMovimentos.getValueAt(tableMovimentos.getSelectedRow(),0));
        dao.eliminar(c);
        
        
        
        readTableMovimentos();
        String t=Integer.toString(cx.obterSaldo(s));
        
        tpnSaldo.setText(t);
        
        
        
    
    }else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser excluída!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    public void readTableMovimentos(){
       DefaultTableModel modelo= (DefaultTableModel) tableMovimentos.getModel();
       modelo.setNumRows(0);
       Caixa s=new Caixa();
       CaixaDAO cx=new CaixaDAO();
       tableMovimentos.getColumnModel().getColumn(0).setPreferredWidth(20);
       tableMovimentos.getColumnModel().getColumn(1).setPreferredWidth(250);
       tableMovimentos.getColumnModel().getColumn(2).setPreferredWidth(250);
       tableMovimentos.getColumnModel().getColumn(3).setPreferredWidth(250);
      tableMovimentos.getColumnModel().getColumn(4).setPreferredWidth(250);
      
       MovimentoDAO dao=new MovimentoDAO();
       
      
       for(Movimento c: dao.Read()){
       
       modelo.addRow(new Object[]{
       c.getNumero(),
       c.getDescricao(),
       c.getData_hora(),
       c.getValor(),
       c.getTipo()
      
       
       });
       
       
       }
    String t=Integer.toString(cx.obterSaldo(s));
        
        tpnSaldo.setText(t);
       }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirMovimento;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMovimentos;
    private javax.swing.JTextPane tpnSaldo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
