package viewUsuarioComum;

import viewAdimnistrador.MenuAdministrador;
import dao.EstoqueDAO;
import dao.ServicoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.EstoqueModel;
import model.Servico;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class ServicosUsuarioComum extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeEndereco
     */
    public ServicosUsuarioComum() {
        initComponents();
        this.setSize(570,470);
        this.setLocationRelativeTo(null);
         DefaultTableModel modelo= (DefaultTableModel) tableServicos.getModel();
       tableServicos.setRowSorter( new TableRowSorter(modelo));
       readTableServicos();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnInserirServico = new javax.swing.JButton();
        btnAterar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableServicos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Serviços");
        setName("frameServiçosUsuarioComum"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(null);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(20, 390, 70, 23);

        btnInserirServico.setText("Inserir");
        btnInserirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirServicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirServico);
        btnInserirServico.setBounds(80, 60, 90, 23);

        btnAterar.setText("Alterar");
        btnAterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAterar);
        btnAterar.setBounds(200, 60, 100, 23);

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescricao);
        txtDescricao.setBounds(20, 30, 187, 20);
        jPanel1.add(txtPreco);
        txtPreco.setBounds(250, 30, 122, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Descrição");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 90, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Preço");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 10, 70, 15);

        tableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Preço"
            }
        ));
        tableServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableServicos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 520, 250);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(330, 60, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        MenuAdministrador a= new MenuAdministrador();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnInserirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirServicoActionPerformed
     Servico c=new Servico();
        ServicoDAO dao=new ServicoDAO();
        
        c.setDescricao(txtDescricao.getText());
        
         int intPreco=Integer.parseInt(txtPreco.getText());
        c.setPreco(intPreco);
       
        
        
        dao.adicionar(c);
        readTableServicos();
    }//GEN-LAST:event_btnInserirServicoActionPerformed

    private void tableServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServicosMouseClicked
        if (tableServicos.getSelectedRow() !=-1)
    {
    
    txtDescricao.setText(tableServicos.getValueAt(tableServicos.getSelectedRow(), 1).toString());
    txtPreco.setText(tableServicos.getValueAt(tableServicos.getSelectedRow(), 2).toString());
    
    }
    
    }//GEN-LAST:event_tableServicosMouseClicked

    private void btnAterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAterarActionPerformed
       if (tableServicos.getSelectedRow() !=-1)
    {
     Servico c=new Servico();
        ServicoDAO dao=new ServicoDAO();
        
        c.setDescricao(txtDescricao.getText());
        int intPreco=Integer.parseInt(txtPreco.getText());
        c.setPreco(intPreco);
        
        c.setCodigo((int)tableServicos.getValueAt(tableServicos.getSelectedRow(),0));
        dao.alterar(c);
        txtDescricao.setText("");
        txtPreco.setText("");
        
        readTableServicos();
    
    }
      else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser alterada!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tableServicos.getSelectedRow() !=-1)
    {
     Servico c=new Servico();
        ServicoDAO dao=new ServicoDAO();
        
       
        
        c.setCodigo((int)tableServicos.getValueAt(tableServicos.getSelectedRow(),0));
        dao.eliminar(c);
        txtDescricao.setText("");
        txtPreco.setText("");
        
        readTableServicos();
    
    }
      else
        {
        JOptionPane.showMessageDialog(null, "Selecione a linha a ser excluida!", "erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
 public void readTableServicos(){
       DefaultTableModel modelo= (DefaultTableModel) tableServicos.getModel();
       modelo.setNumRows(0);
       tableServicos.getColumnModel().getColumn(0).setPreferredWidth(50);
       tableServicos.getColumnModel().getColumn(1).setPreferredWidth(250);
       tableServicos.getColumnModel().getColumn(2).setPreferredWidth(250);
      
      
       ServicoDAO dao=new ServicoDAO();
       
       for(Servico c: dao.Read()){
       
       modelo.addRow(new Object[]{
       c.getCodigo(),
       c.getDescricao(),
       c.getPreco()
      
       
       });
       
       
       }
    
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicosUsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicosUsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicosUsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicosUsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicosUsuarioComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirServico;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableServicos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
