package viewControl;



import dao.UsuarioDAO;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Usuario;
import viewAdimnistrador.MenuAdministrador;
import viewUsuarioComum.MenuUsuarioComum;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JNCA celular
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form PagInicial
     */
    public Login() {
       
        initComponents();
        setSize(800,440);
        setLocationRelativeTo( null );
        
        
    }
private void ConfirmarSaida(){



}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        pnlBenvindo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlCriarConta = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        pwdSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnCriarConta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(522, 375));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        Panel1.setBackground(new java.awt.Color(255, 204, 102));
        Panel1.setMaximumSize(new java.awt.Dimension(0, 0));
        Panel1.setMinimumSize(new java.awt.Dimension(0, 0));
        Panel1.setPreferredSize(new java.awt.Dimension(522, 375));
        Panel1.setLayout(null);

        pnlBenvindo.setBackground(new java.awt.Color(255, 204, 102));
        pnlBenvindo.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Benvindo!");
        pnlBenvindo.add(jLabel6);
        jLabel6.setBounds(230, 100, 150, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones50percent/InfinityLogo.png"))); // NOI18N
        pnlBenvindo.add(jLabel5);
        jLabel5.setBounds(20, 40, 200, 120);

        Panel1.add(pnlBenvindo);
        pnlBenvindo.setBounds(0, 0, 380, 400);

        pnlCriarConta.setBackground(new java.awt.Color(255, 204, 102));
        pnlCriarConta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlCriarConta.setLayout(null);

        btnLogin.setBackground(new java.awt.Color(255, 255, 230));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlCriarConta.add(btnLogin);
        btnLogin.setBounds(30, 240, 330, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome");
        pnlCriarConta.add(jLabel1);
        jLabel1.setBounds(30, 110, 60, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Senha");
        pnlCriarConta.add(jLabel2);
        jLabel2.setBounds(30, 170, 34, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        pnlCriarConta.add(jLabel3);
        jLabel3.setBounds(220, 50, 240, 50);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        pnlCriarConta.add(txtNome);
        txtNome.setBounds(30, 130, 330, 30);

        pwdSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdSenhaActionPerformed(evt);
            }
        });
        pnlCriarConta.add(pwdSenha);
        pwdSenha.setBounds(30, 190, 330, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 230));

        btnCriarConta.setBackground(new java.awt.Color(255, 255, 255));
        btnCriarConta.setText("Cria uma conta");
        btnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ainda não tem uma conta?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriarConta)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCriarConta)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pnlCriarConta.add(jPanel2);
        jPanel2.setBounds(0, 340, 390, 40);

        Panel1.add(pnlCriarConta);
        pnlCriarConta.setBounds(390, 0, 410, 400);

        getContentPane().add(Panel1);
        Panel1.setBounds(0, 0, 800, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        UsuarioDAO u=new UsuarioDAO();
        Usuario user=new Usuario();
        
        user.setNome(txtNome.getText());
        user.setSenha(pwdSenha.getText());
        u.ValidarUsuario(user);
        
        if(user==null)
        {
         JOptionPane.showMessageDialog(null,"Dados incorrectos!");
    
        }
        else{
            switch(user.getTipoUsuario())
            {
                case"Admnistrador":
                JOptionPane.showMessageDialog(null,"Dados correctos!");
                 MenuAdministrador a=new MenuAdministrador();
                 user.setTipoUsuario("Amnistrador");
                  
                    a.setVisible(true);
                    setVisible(false);
                    dispose();
                    break;
                 case"Comum":
                 JOptionPane.showMessageDialog(null,"Dados correctos!");
                    MenuUsuarioComum b=new MenuUsuarioComum();
                    user.setTipoUsuario("Comum");
                    b.setVisible(true);
                    setVisible(false);
                    dispose();
                    break;
                    
            }
            
            
            
            }
        
                    
        
       
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void pwdSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdSenhaActionPerformed

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
       CriarConta a= new CriarConta();
     a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCriarContaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        JOptionPane sair = new JOptionPane();
        int Sair = JOptionPane.showConfirmDialog(null,"Você deseja sair do programa?","Sair",JOptionPane.YES_NO_OPTION);
      if(Sair == JOptionPane.YES_OPTION){
        System.exit(0);
       this.dispose();

      }else{
         if(Sair == JOptionPane.NO_OPTION){
setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         }
      }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlBenvindo;
    private javax.swing.JPanel pnlCriarConta;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
